config/routes.rb
Rails.application.routes.draw do

  resources :vehicles do
      resources :repairs
  end
    

  get 'maintenance/show'

  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'home#index'

end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :vehicle
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :vehicles, dependent: :destroy
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user
  has_many :repairs, dependent: :destroy
  has_attached_file :vehicleimage, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default-vehicle.png"  
  validates_attachment_content_type :vehicleimage, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
                                                                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/maintenance_controller.rb
class MaintenanceController < ApplicationController
  def show
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  include ActionView::Helpers::NumberHelper
    
  before_action :set_repair, only: [:show, :edit, :update, :destroy]
  before_action :get_vehicle

  respond_to :html

  def get_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end
    
  def index
    @repairs = @vehicle.repairs.all
    @totalcost = 0
    @repairs.each do |repair|
        @totalcost += repair.cost
    end
    @totalcost = number_to_currency(@totalcost)
    respond_with(@repairs)
  end

  def show
    respond_with(@repair, :location => vehicle_repairs_path(@vehicle))
  end

  def new
    @repair = Repair.new
    respond_with(@vehicle, @repair)
  end

  def edit
  end

  def create
    @repair = @vehicle.repairs.new(repair_params)
    @repair.save
    respond_with(@repair, :location => vehicle_repairs_path(@vehicle))
  end

  def update
    @repair.update(repair_params)
    respond_with(@repair, :location => vehicle_repairs_path(@vehicle))
  end

  def destroy
    @repair.destroy
    respond_with(@repair)
  end

  private
    def set_repair
      @repair = Repair.find(params[:id])
    end

    def repair_params
      params.require(:repair).permit(:vehicle_id, :shop, :cost, :mileage, :work, :date)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #    super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @vehicles = Vehicle.where("user_id = ?", current_user.id).all
    respond_with(@vehicles)
  end

  def show
    respond_with(@vehicle)
  end

  def new
    @vehicle = Vehicle.new
    respond_with(@vehicle)
  end

  def edit
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user_id = current_user.id
    @vehicle.save
    flash.notice = "Vehicle created succesfully"
    respond_with(@vehicle, :location => vehicles_path)
  end

  def update
    @vehicle.update(vehicle_params)
    respond_with(@vehicle, :location => vehicles_path)
  end

  def destroy
    @vehicle.destroy
    flash.notice = "Vehicle succesfully removed"
    respond_with(@vehicle)
  end

  private
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    def vehicle_params
      params.require(:vehicle).permit(:user_id, :year, :make, :model, :vehicleimage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maintenance_helper.rb
module MaintenanceHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/_footer.html.erb
<span>Made by Steve Plesha - <a href="http://steveplesha.com">steveplesha.com</a> - <a href="http://www.twitter.com/steveplesha">@steveplesha</a> on Twitter</span>

app/views/layouts/_navigation.html.erb
<div class="hidden-sm hidden-md hidden-lg">
    <nav class="main-nav">
        <ul class="nav collapsed">
            <li class="menu-label">
                <span class="glyphicon glyphicon-menu-hamburger"></span> Menu
            </li>
            <ul class="main-nav-toggle">
                <li>
                    <%= link_to (root_path) do %>
                        <span>CarLife Home</span>  
                        <i class="nav-image home-icon"></i>
                    <% end %>
                </li>
                <% if current_user %>
                   <li>
                    <%= link_to (vehicles_path) do %>
                        <span>Your Cars</span>
                        <i class="nav-image car-icon"></i>
                    <% end %>
                    </li>
                <% end %>
                <% if !current_user %>
                <li>
                    <%= link_to (new_user_session_path) do %>
                        <span>Login</span>
                        <i class="nav-image login-icon"></i>
                    <% end %>
                </li>
                <% end %>
                <% if !current_user %>        
                    <li>
                        <%= link_to (new_user_registration_path) do %>
                            <span>Register</span>
                            <i class="nav-image register-icon"></i>
                        <% end %>
                    </li>
                <% end %>
                <% if current_user %>        
                    <li>
                        <%= link_to (new_vehicle_path) do %>
                            <span>Add Car</span>
                            <i class="nav-image add-car-icon"></i>
                        <% end %>
                    </li>
                <% end %>
                <li>
                    <%= link_to (maintenance_show_path) do %>
                        <span>Maintenance</span>
                        <i class="nav-image engine-icon"></i>
                    <% end %>
                </li>   
                <% if current_user %>      
                   <li>     
                        <%= link_to (edit_user_registration_path) do %>
                            <span>Your Profile</span>
                            <i class="nav-image profile-icon"></i>
                        <% end %>
                    </li>
                <% end %>
                <% if current_user %>        
                    <li>
                        <%= link_to destroy_user_session_path, method: :delete do %>
                            <span>Logout</span>
                            <i class="nav-image logout-icon"></i>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </ul>
    </nav>
    <div class="pull-right login-state">
        <% if current_user %>
            <span>Logged in</span>
        <% else %>
            <span>Not logged in</span>
        <% end %>
    </div>
</div>

 
<div class="hidden-xs">
    <nav class="main-nav">
        <ul class="nav">
            <li class="menu-label"><span class="glyphicon glyphicon-menu-hamburger"></span> Menu</li>
            <li>
                <%= link_to (root_path) do %>
                    <span>CarLife Home</span>    
                    <i class="nav-image home-icon"></i>
                <% end %>
            </li>
            <% if current_user %>
               <li>
                <%= link_to (vehicles_path) do %>
                    <span>Your Cars</span>
                    <i class="nav-image car-icon"></i>
                <% end %>
                </li>
            <% end %>
            <% if !current_user %>
            <li>
                <%= link_to (new_user_session_path) do %>
                    <span>Login</span>
                    <i class="nav-image login-icon"></i>
                <% end %>
            </li>
            <% end %>
            <% if !current_user %>        
                <li>
                    <%= link_to (new_user_registration_path) do %>
                        <span>Register</span>
                        <i class="nav-image register-icon"></i>
                    <% end %>
                </li>
            <% end %>
            <% if current_user %>        
                <li>
                    <%= link_to (new_vehicle_path) do %>
                        <span>Add Car</span>
                        <i class="nav-image add-car-icon"></i>
                    <% end %>
                </li>
            <% end %>
            <li>
                <%= link_to (maintenance_show_path) do %>
                    <span>Maintenance</span>
                    <i class="nav-image engine-icon"></i>
                <% end %>
            </li>   
            <% if current_user %>      
               <li>     
                    <%= link_to (edit_user_registration_path) do %>
                        <span>Your Profile</span>
                        <i class="nav-image profile-icon"></i>
                    <% end %>
                </li>
            <% end %>
            <% if current_user %>        
                <li>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                        <span>Logout</span>
                        <i class="nav-image logout-icon"></i>
                    <% end %>
                </li>
            <% end %>
        </ul>
    </nav>
    <div class="pull-right login-state">
        <% if current_user %>
            <span>Logged in</span>
        <% else %>
            <span>Not logged in</span>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="CarLife is an app enabling you to track the life of your car to keep it running - oil changes, fluid flushes - and track how much you've spent on your vehicle maintenance. ">
    <title>CarLife</title>
    <%= stylesheet_link_tag 'normalize.scss' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="http://fonts.googleapis.com/css?family=Josefin+Sans:400,700,400italic" rel="stylesheet" type="text/css">
    <%= csrf_meta_tags %>
</head>
<body>
    <header>
       <%= render 'layouts/navigation' %>
    </header>
    <main>
        <% if flash || notice %>
            <div class="container">
                <div>
                    <% if notice %>
                        <p class="message info-message"><%= notice %></p>
                    <% elsif alert %>
                        <p class="message error-message"><%= alert %></p>    
                    <% end %>
                </div>
            </div>
        <% end %>
        <div class="content">
            <%= yield %>
        </div>
    </main>
    <footer>
        <%= render 'layouts/footer' %>
    </footer>
</body>
</html>

app/views/maintenance/show.html.erb
<div class="container center-form">
    <h1>Recommended Maintenance</h1>
    <h2>This is a list of general recommended maintenance</h2>
    <h2>Your vehicle may differ, please check your owner's manual</h2>
    
    <ul>
        <li>Oil Change - Every 3,000 miles</li>
        <li>Cabin Air Filter - Every 15,000 miles</li>
        <li>Engine Air Filter - Every 10,000 miles</li>
        <li>Radiator Flush - Every 30,000 miles</li>
        <li>Transmission Fluid Flush - Every 20,000 miles</li>
        <li>Power Steering Fluid Flush - Every 30,000 miles</li>
        <li>Fuel Injection Cleaning - Every 15,000 miles</li>
        <li>Serpentine Belt - Every 40,000 miles</li>
        <li>Battery - Every 3 to 5 years</li>
        <li>Spark Plugs - Every 70,000 miles</li>
    </ul>
</div>

app/views/repairs/_form.html.erb
<%= form_for ([@vehicle, @repair]) do |f| %>
  <% if @repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
      <% @repair.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :work %><br>
    <%= f.text_field :work, class: "form-control", placeholder: "enter work done on car" %>
  </div>
  <div class="field form-group">
    <%= f.label :cost %><br>
    <%= f.text_field :cost, class: "form-control", placeholder: "enter cost of work done"  %>
  </div>
  <div class="field form-group">
    <%= f.label :shop %><br>
    <%= f.text_field :shop, class: "form-control", placeholder: "enter business that did the work" %>
  </div>  
  <div class="field form-group">
    <%= f.label :date %><br>
    <%= f.date_field :date, class: "form-control", placeholder: "enter date when work was done" %>
  </div>
  <div class="field form-group">
    <%= f.label :mileage %><br>
    <%= f.number_field :mileage, class: "form-control", placeholder: "enter mileage of car when work was done" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/repairs/edit.html.erb
<div class="container center-form">
    <h1>Editing repair</h1>

    <%= render 'form' %>

    <%= link_to 'Back', vehicle_repairs_path %>
</div>

app/views/repairs/index.html.erb
<div class="container">
    <h2>Repairs for <%= @vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %></h2>
    <%= image_tag(@vehicle.vehicleimage, class: "car-image-preview") %>
    <h2>Total cost of repairs for this vehicle is <%= @totalcost %></h2>         
</div>           
<div class="container-fluid">
    <div class="row">
        <% @vehicle.repairs.each do |repair| %>
            <div class="repair-item col-xs-10 col-xs-offset-1 col-sm-3 col-sm-offset-1 col-md-3 col-md-offset-1">
               <ul>
                    <li>
                       <h2><%= repair.work %>
                            <span class="repair-edit"> - 
                                <span class="glyphicon glyphicon-pencil"> </span>
                                <%= link_to 'Edit', edit_vehicle_repair_path(@vehicle, repair) %>
                            </span>
                        </h2>
                    </li>
                    <li>Cost: <%= repair.cost %></li>
                    <li>Repair Shop: <%= repair.shop %></li>
                    <li>Date of Work: <%= repair.date %></li>
                    <li>Mileage when work done: <%= repair.mileage %></li>
                </ul>
            </div>
        <% end %>
    </div>
</div>
<div class="container">
    <%= link_to 'New Repair', new_vehicle_repair_path, class: "btn btn-primary" %>
</div>

app/views/repairs/new.html.erb
<div class="container center-form">
    <h1>New repair</h1>

    <%= render 'form' %>

    <%= link_to 'Back', vehicle_repairs_path %>
</div>

app/views/repairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle:</strong>
  <%= @repair.vehicle %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @repair.shop %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @repair.cost %>
</p>

<p>
  <strong>Mileage:</strong>
  <%= @repair.mileage %>
</p>

<p>
  <strong>Work:</strong>
  <%= @repair.work %>
</p>

<p>
  <strong>Date:</strong>
  <%= @repair.date %>
</p>

<%= link_to 'Edit', edit_vehicle_repair_path(@repair) %> |
<%= link_to 'Back', vehicle_repairs_path %>

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field form-group">
      <%= f.label :year %><br>
      <%= f.number_field :year, class: 'form-control', placeholder: "enter year car was made" %>
  </div>  
  <div class="field form-group">
      <%= f.label "Manufacturer" %><br>
      <%= f.text_field :make, class: 'form-control', placeholder: "enter manufacturer of car" %>
  </div>
  <div class="field form-group">
      <%= f.label :model %><br>
      <%= f.text_field :model, class: 'form-control', placeholder: "enter model of car" %>
  </div>
  <h2>Image</h2>
  <h3>Current Image</h3>
  <%= image_tag("default-vehicle.png", class: "car-image-preview") %>
  <div class="field form-group">
      <%= f.label :vehicleimage %><br>
      <%= f.file_field :vehicleimage %>
  </div>
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<div class="container center-form">
<h1>Edit car information:</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>
</div>

app/views/vehicles/index.html.erb
<% if @vehicles.empty? %>
    <div class="container">
        <h1>You don't have any cars added yet!</h1>
        <h2>Click the button to add one now</h2>
    </div>
<% else %> 
       <div class="carlist row">   
        <% @vehicles.each do |vehicle| %>
           <div class="car-item col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-1 col-md-4 col-md-offset-1">
                <h1 class="car-item-title"><%= vehicle.year %> <%= vehicle.make %> <%= vehicle.model %></h1>
                <%= image_tag(vehicle.vehicleimage, class: "car-image") %>
                <div class="dropdown">
                       <button class="dropdown btn btn-car-item" type="button" data-toggle="dropdown" href="#">Menu <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'Edit Car Info/Picture', edit_vehicle_path(vehicle) %></li>
                            <li><%= link_to 'Show Repairs List/Add', vehicle_repairs_path(vehicle) %></li>
                            <li><%= link_to 'Delete This Car', vehicle, method: :delete, data: { confirm: "Are you sure? This can't be undone" }, class: "delete-link" %></li>
                        </ul>
                </div>
            </div>
        <% end %>
    </div>
<% end %>
<div class="container">
    <%= link_to 'New Vehicle', new_vehicle_path, class: "btn btn-primary" %>
</div>

app/views/vehicles/new.html.erb
<div class="container center-form">
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>
</div>

app/views/vehicles/show.html.erb
<div class='container center-form'>
<p id="notice"><%= notice %></p>

<p>
  <%= @vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %> 
</p>

<%= image_tag("default-vehicle.png", class: "car-image") %>


<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>
</div>